name: Publish Website

on:
  push:
    branches:
      - trunk
  workflow_dispatch:
jobs:
  Build-Artifact-Action:
    name: Build-Artifact-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install PHP dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        php_version: 8.1

    - name: Install Acorn
      run: composer require roots/acorn

    - name: Setup node 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Run yarn install
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Run yarn build
      uses: borales/actions-yarn@v4
      with:
        cmd: build

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
        name: repository-artifact
        path: |
          .
          !.DS_Store
          !.git 
          !.gitattributes 
          !.github 
          !.gitignore 
          !.editorconfig.json 
          !README.md 
          !composer.json 
          !composer.lock 
          !package-lock.json 
          !package.json 
          !travis.yml 
          !phpcs.xml.dist 
          !node_modules 
          !yarn.lock
